### ISSUE TITLE
Installer for binaries direct download and install

### ISSUE THREAD

**Issue by lolautruche** [platformsh/cli#25]
The legacy CLI provides an [installer written in PHP](https://github.com/platformsh/legacy-cli/blob/main/dist/installer.php) to ease to install process.

We should provide the same kind of script for the Go CLI to serve the same purpose, especially for automated systems (e.g., CI/CD services).
We can get inspired by the [Symfony CLI installer](https://github.com/symfony-cli/symfony-cli/blob/main/installer/bash-installer), which is written in Bash.

### Requirements
- Must be language agnostic (Bash script seems to be a good approach)
- Windows can probably be ignored (we can still provide a powershell, but not sure it worths it)
- CLI Binaries must be dependency free (which is currently not the case for macOS, see #26)

**Comment by gggeek** [comment]
Agree.

Current install recipe based on Brew might be ok for developer's laptops, which are often running on MacOS, but it is a bit of a chore (overkill) for linux installs running in server/container environments. FWIV, i just tried installing Brew in order to then get the cli, and the installation process of brew by itself took more than one minute - no idea how much disk space it chewed up, but it definitely was north of 720MB!

**Comment by akalipetis** [comment]
We could potentially use something like this: https://github.com/jpillora/installer
We could host it and only allow the our CLI route.
