### ISSUE TITLE
Remove dependency on `oniguruma` and `openssl` on macOS

### ISSUE THREAD

**Issue by lolautruche** [platformsh/cli#26]
The macOS binary is currently not completely independent as it requires external dependencies: `oniguruma` and `openssl`.
These dependencies are resolved when using Homebrew to install the binary, but make it hard to install the CLI independently (CLI direct download).

**Comment by lolautruche** [comment]
After discussing with @pjcdawkins, I think we can safely remove `oniguruma` dependency for `mbstring` as multibyte regexp are not used in the legacy CLI. We'd need to compile `mbstring` with `--disable-mbregex` flag.

**Comment by pjcdawkins** [comment]
No need to include the `mbstring` extension at all; it isn't required by the legacy CLI.

```
$ composer why ext-mbstring   
There is no installed package depending on "ext-mbstring"
```

**Comment by lolautruche** [comment]
As for `openssl` extension: macOS Ventura comes with LibreSSL 3.3, which seems to be compatible with PHP 8.2.

**Comment by vintorez** [comment]
**OpenSSL Problem:**
Latest versions of MacOS come with OpenSSL/LibreSSL. 
But they contain only binary files, while to build PHP we don't need binary files.
We need OpenSSL/LibreSSL in the form of dynamic or static library.
MacOS doesn't provide that kind of libraries.
So there is no way to link PHP and OpenSSL/LibreSSL binary file.

**Solution:**
The only solution is to download source code and build a dynamic or static library, so after that we could compile PHP using this library.

**Dynamic vs static:**

- If we build dynamic library, we have to keep it somewhere in the file system, so that PHP always has access to it.
- If we build static library, we can directly include it into PHP binary file. So no need to worry about the library at all, we can delete it. But in this case, the size of the PHP binary file will become **~2.5Mb** larger.

**Cons:**
The main drawback of this solution is that compiling the OpenSSL/LibreSSL libraries is time consuming:
- brew openssl + build php **≈ 4-5min**
- compile openssl + build php **≈ 9-10min**
